export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_POKEMON_DETAIL';
export const GET_ALL_TYPES = 'GET_ALL_TYPES';
export const FILTER_BY_POKEMON_TYPE = 'FILTER_BY_POKEMON_TYPE';
export const ORDER_BY_POKEMON_NAME = 'ORDER_BY_POKEMON_NAME';
export const ORDER_BY_POKEMON_ATTACK = 'ORDER_BY_POKEMON_ATTACK';
export const SET_FILTER_OPTIONS = 'SET_FILTER_OPTIONS';